import numpy as np
from sklearn.tree import DecisionTreeClassifier
import m2cgen as m2c

print("Generating synthetic psychiatric marker data...")

# 1. Create Mock Data (1000 samples, 52 facial blendshapes)
n_samples = 1000
X = np.random.rand(n_samples, 52) * 0.3  # Base resting face values
y = np.zeros(n_samples) # Default to 0 ("Normal")

# Simulate Class 1 ("Frustrated" / Stressed / Anxious)
# High jaw tension, brow furrowing, tight lips
# Blendshape approx indices: browDown=1,2, jawForward=23, mouthPress=36,37
X[300:600, [1, 2, 23, 36, 37]] += 0.6
y[300:600] = 1

# Simulate Class 2 ("Lethargic" / Depressed)
# Heavy eyelids, downward gaze, slight frown, low facial energy
# Blendshape approx indices: eyeBlink=9,10, eyeLookDown=11,12, mouthFrown=30,31
X[600:1000, [9, 10, 11, 12, 30, 31]] += 0.6
y[600:1000] = 2

print("Training Decision Tree Classifier...")
# 2. Train the Model
# We limit depth to 5 so the resulting JavaScript is lightweight and lightning fast
clf = DecisionTreeClassifier(max_depth=5, random_state=42)
clf.fit(X, y)

print("Converting model to JavaScript...")
# 3. Export to raw JavaScript
raw_js = m2c.export_to_javascript(clf, function_name="compute_score")

# 4. Add the React Wrapper
# This translates the math output (0, 1, 2) into the exact text strings your React app expects
wrapper_code = """// src/clinical_model.js
// AUTO-GENERATED BY M2CGEN

export function score(input) {
    const raw_prediction = compute_score(input);
    if (raw_prediction === 0) return "Normal";
    if (raw_prediction === 1) return "Frustrated";
    if (raw_prediction === 2) return "Lethargic";
    return "Normal";
}

"""

final_code = wrapper_code + raw_js

# 5. Save the output
with open("clinical_model.js", "w") as f:
    f.write(final_code)

print("\nSuccess! Your model has been trained and exported.")
print("Check the same folder for the 'clinical_model.js' file.")