// src/clinical_model.js
// AUTO-GENERATED BY M2CGEN

export function score(input) {
    const raw_prediction = compute_score(input);
    if (raw_prediction === 0) return "Normal";
    if (raw_prediction === 1) return "Frustrated";
    if (raw_prediction === 2) return "Lethargic";
    return "Normal";
}

function compute_score(input) {
    var var0;
    if (input[31] <= 0.44987910985946655) {
        if (input[1] <= 0.4503091275691986) {
            var0 = [1.0, 0.0, 0.0];
        } else {
            var0 = [0.0, 1.0, 0.0];
        }
    } else {
        var0 = [0.0, 0.0, 1.0];
    }
    return var0;
}
