// src/clinical_model.js
// AUTO-GENERATED BY M2CGEN

export function score(input) {
    const raw_prediction = compute_score(input);
    
    // Find the index of the highest score (the 1.0) in the array
    const maxIndex = raw_prediction.indexOf(Math.max(...raw_prediction));
    
    if (maxIndex === 0) return "Normal";
    if (maxIndex === 1) return "Frustrated";
    if (maxIndex === 2) return "Lethargic";
    
    return "Normal"; // Fallback just in case
}

function compute_score(input) {
    var var0;
    if (input[31] <= 0.44987910985946655) {
        if (input[1] <= 0.4503091275691986) {
            var0 = [1.0, 0.0, 0.0];
        } else {
            var0 = [0.0, 1.0, 0.0];
        }
    } else {
        var0 = [0.0, 0.0, 1.0];
    }
    return var0;
}
